name: generate-snake
on:
  # 每 12 小时自动运行一次
  schedule:
    - cron: "0 */12 * * *"
 
  # 允许手动触发执行
  workflow_dispatch:
 
  # 每当push到master分支时自动执行
  push:
    branches:
    - master
    - main
 
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
 
    steps:
      - uses: Platane/snk@v3
        with:
           github_user_name: ${{ github.repository_owner }}
           outputs: |
              public/github-snake.svg
              public/github-snake-dark.svg?palette=github-dark
              public/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
     
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
